### ISSUE TITLE
Botがクラッシュ落ちする問題

### ISSUE THREAD

**Issue by notsmatch** [notsmatch/KyoshuBot#23]
原因究明中

**Comment by notsmatch** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/46530214/83466864-5c212a00-a4b3-11ea-9660-1c05d436313a.png)

**Comment by notsmatch** [comment]
discord.com買収によるドメイン変更が関係しているかもしれないため、JDAに関する依存関係のバージョンを最新のものに変更
https://github.com/notsmatch/KyoshuBot/commit/699045784e50e7bdb5e94ea4d3f32660382b8ea8

**Comment by notsmatch** [comment]
UserIDからUserを取得する際にdiscordapp.comへのAPIリクエストを送信しているため、discord.comに変更されてしまったのが原因かと。

**Comment by notsmatch** [comment]
``
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
[JDA MainWS-ReadThread] INFO JDA - Successfully resumed Session!
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
[JDA MainWS-ReadThread] INFO JDA - Successfully resumed Session!
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
[JDA MainWS-ReadThread] INFO JDA - Successfully resumed Session!
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
[JDA MainWS-ReadThread] INFO JDA - Successfully resumed Session!
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
[JDA MainWS-ReadThread] INFO JDA - Successfully resumed Session!
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
[JDA MainWS-ReadThread] INFO JDA - Successfully resumed Session!
[JDA Gateway-Worker 1] WARN WebSocketClient - Missed 2 heartbeats! Trying to reconnect...
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
[JDA MainWS-WriteThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
com.mongodb.MongoInterruptedException: Interrupted acquiring a permit to retrieve an item from the pool 
	at com.mongodb.internal.connection.ConcurrentPool.acquirePermit(ConcurrentPool.java:203)
	at com.mongodb.internal.connection.ConcurrentPool.get(ConcurrentPool.java:140)
	at com.mongodb.internal.connection.ConcurrentPool.get(ConcurrentPool.java:123)
	at com.mongodb.internal.connection.PowerOfTwoBufferPool.getBuffer(PowerOfTwoBufferPool.java:78)
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:105)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:588)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:445)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)
	at com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:731)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725)
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:196)
	at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:211)
	at me.notsmatch.kyoshubot.service.MongoService.findGuildSettingsDocById(MongoService.kt:56)
	at me.notsmatch.kyoshubot.service.GuildSettingsService.getGuildSettings(GuildSettingsService.kt:9)
	at me.notsmatch.kyoshubot.command.CanCommand.execute(CanCommand.kt:24)
	at com.jagrosh.jdautilities.command.Command.run(Command.java:321)
	at com.jagrosh.jdautilities.command.impl.CommandClientImpl.onMessageReceived(CommandClientImpl.java:557)
	at com.jagrosh.jdautilities.command.impl.CommandClientImpl.onEvent(CommandClientImpl.java:445)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:166)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:921)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:808)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:786)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:959)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at com.mongodb.internal.connection.ConcurrentPool.acquirePermit(ConcurrentPool.java:199)
	... 48 more
[JDA Gateway-Worker 1] WARN WebSocketClient - Missed 2 heartbeats! Trying to reconnect...
[JDA MainWS-WriteThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session
``

**Comment by notsmatch** [comment]
もう訳がわからないよ
